#!/usr/bin/env node

'use strict';

var aws = require('aws-sdk');
var HttpsProxyAgent = require('https-proxy-agent');
var argv = require('yargs').argv;
var Table = require('cli-table');
var fs = require('fs');
var prompt = require('prompt');
var events = require('events');
var app = new events.EventEmitter();

app.on('quit', function() {
    console.log("Quitting");
    process.exit(0);
});

if(argv.hasOwnProperty('profile'))
	var profileToUse = argv.profile;
else
	var profileToUse = 'default';
var credentials = new aws.SharedIniFileCredentials({profile: profileToUse});
aws.config.credentials = credentials;

if (typeof process.env.https_proxy !== 'undefined') {
  aws.config.update({
    httpOptions: {
      agent: new HttpsProxyAgent(process.env.https_proxy)
    }
  });
}

if(argv.hasOwnProperty('region'))
	var regionToUse = argv.region;
else
	var regionToUse = 'ap-southeast-2';
var ec2 = new aws.EC2({region: regionToUse});

var constructed=[];
var table = new Table({
    head: ['','Name','Status','Creation Time']
  , colWidths: [5,50,20,50]
});

// Prompt Schema for input prompt
var deleteListSchema = {
    properties: {
      deleteList: {
     	description: "Enter a comma-separated list of stacks to delete (Example : 1-4,6,7), or q to quit.",
        required: true
      }
    }
  };

var confirmationSchema = {
    properties: {
      confirmation: {
     	description: "Confirm delete ? [yes/no]",
        required: true
      }
    }
  };

var cf = new aws.CloudFormation({region:regionToUse});

function usage()
{
	console.log("Usage");
	console.log("---------------------------------------------------------");
	console.log(process.argv[1] + " [--action action] [--profile profileName] [--region awsRegion] [--filterByStatus status] [--pattern pattern] [--help]");
	console.log("action: Action to perform ,currently supported : list , delete");
	console.log("profile: AWS profile to use, defaults to 'default' profile");
	console.log("region: AWS region to use, defaults to 'ap-southeast-2'");
	console.log("filterByStatus: Filter by AWS CloudFormation status");
	console.log("pattern: Matching pattern, '*' wildcard supported");
	console.log("   N.B. '' quotes are required for wildcards to prevent the shell from interpolating them");
	console.log("   e.g. ./cfmgr --pattern 'myproject-.*' to list all the stacks with the prefix of myproject-");
	console.log("help: Display this usage message");
}
var foundStacks = [];
function findStacks(params,callback){
	(function(params,foundStacks,callback) {
          cf.listStacks(params,function(err,res){
		if(err){
			console.log(err);
			callback(err);
		}
		else {
                    if (typeof res.StackSummaries !== 'undefined') {
                        for (var i = 0; i < res.StackSummaries.length; i++) {
                            // if we want to list stacks to delete, then
                            // any stack that is in DELETE_IN_PROGRESS or DELETE_COMPLETE
                            // should be skipped in the listings
                            if (argv.action === 'delete') {
                                if (res.StackSummaries[i].StackStatus.match(/^DELETE_(IN_PROGRESS|COMPLETE)$/)) {
                                    continue;
                                }
                            }
                            if(argv.hasOwnProperty('pattern')){
                                if(res.StackSummaries[i].StackName.match(argv.pattern) !== null){
                                    foundStacks.push(res.StackSummaries[i]);
                                }
                            }
                            else{
                                foundStacks.push(res.StackSummaries[i]);
                            }
                        }
                    }
			if(typeof res.NextToken !== 'undefined'){
				params.NextToken = res.NextToken;
				findStacks(params,callback);
			}
			else{
				callback(null);
			}
		}
		});
     })(params,foundStacks,callback);
}

if(argv.hasOwnProperty('help')){
	usage();
	process.exit(0);
}

var params = {};

if(!argv.hasOwnProperty('action')){
	argv.action = 'list';
}
else {
  if(argv.action == 'delete' && !argv.hasOwnProperty('filterByStatus')){
    params.StackStatusFilter = [ 'CREATE_IN_PROGRESS','CREATE_FAILED','CREATE_COMPLETE','ROLLBACK_IN_PROGRESS','ROLLBACK_FAILED','ROLLBACK_COMPLETE','DELETE_FAILED','UPDATE_IN_PROGRESS','UPDATE_COMPLETE_CLEANUP_IN_PROGRESS','UPDATE_COMPLETE','UPDATE_ROLLBACK_IN_PROGRESS','UPDATE_ROLLBACK_FAILED','UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS','UPDATE_ROLLBACK_COMPLETE' ]
  }
}

if(argv.hasOwnProperty('filterByStatus')){
	var filters = argv.filterByStatus.split(",");
	params.StackStatusFilter = filters;
}

findStacks(params,function(err){
	if(err){
		console.log(err);
	}
	else{
		var numCounter =0;
		if(foundStacks.length < 1){
			console.log("No stacks found.");
			process.exit(1);
		}
		console.log("Number of stacks found : "+foundStacks.length);
			for(var i=0;i<foundStacks.length;i++){
				table.push([++numCounter,foundStacks[i].StackName,foundStacks[i].StackStatus,foundStacks[i].CreationTime]);
			}
		console.log(table.toString());
		switch(argv.action){
				case 'list':
					process.exit(0);
					break;
				case 'delete':
					var deleteIndex = [];
					prompt.start();
					prompt.message = "";
					prompt.delimiter="";
				 	prompt.get(deleteListSchema, function (err, result) {
					    if (err) { return onErr(err); }
					    var deleteList = result.deleteList.split(",");
                                            if (deleteList[0] === 'q') {
                                                app.emit('quit');
                                            }
					    for(var i=0; i<deleteList.length;i++)
					    {
					    	var subList = deleteList[i].split("-");
					    	var startCount = subList[0];
					    	var endCount;
					    	if(subList.length > 1){
					    		endCount = parseInt(subList[1]);
					    	}
					    	else {
					    		endCount = parseInt(subList[0]);
					    	}
					    	for(var j=startCount;j<=endCount;j++){
					    		if(j<=0 || j>foundStacks.length){
					    			console.log("Invalid input..");
					    			process.exit(1);
					    		}
					    		deleteIndex.push(j);
					    	}
					    }
					    console.log("Will delete the following stacks...");
					    console.log("------------------------------------");
					    for(var i=0;i<deleteIndex[i];i++){
					    	console.log(table[deleteIndex[i]-1][1]);
					    }
					    console.log("------------------------------------");
					    prompt.get(confirmationSchema, function (err, result) {
					    	if(err) {return onErr(err); }
					    	switch(result.confirmation){
					    		case 'yes':
					    			for(var i=0; i< deleteIndex[i];i++){
					    				var params = {
  											StackName: table[deleteIndex[i]-1][1]
										};
										(function(params) {
										cf.deleteStack(params,function(err,data){
											if(err){
												console.log("Error deleting "+params.StackName);
											}
											else {
												console.log("Deleted "+params.StackName+" ...");
											}
										})})(params);
					    			}
					    			break;
					    		case 'no':
					    			process.exit(0);
					    			break;
					    	}
					    });
				  	});

					break;

		}
	}
});

process.on('SIGINT', function() {
    console.log("Caught interrupt signal, exiting.");
    process.exit(0);
});

function onErr(err) {
    console.log("Error encountered: ", err, err.stack);
};
